name: Greenframe Analysis
on: [push, workflow_dispatch]
jobs:
  greenframeci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history
      - run: curl https://assets.greenframe.io/install.sh | bash
      - run: docker-compose build
        working-directory: development
      - run: docker-compose up -d
        working-directory: development
      - run: greenframe analyze --baseURL https://localhost:4000
      - run: greenframe analyze --baseURL https://localhost:3000
        env:
          GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
