name: Greenframe Analysis
on: [push, workflow_dispatch]
jobs:
  greenframeci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history
      - run: curl https://assets.greenframe.io/install.sh | bash
      - run: cd development
      - run: docker-compose build
      - run: docker-compose up -d
      - run: sleep 60 # Wait for the application to start
      - run: greenframe analyze
        env:
          GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
